name: iOSWithCarthageProj
options:
  bundleIdPrefix: com.mothule

targets:
  iOSWithCarthageProj:
    type: application
    platform: iOS
    sources: iOSWithCarthageProj
  iOSWithUTProjTests:
    type: bundle.unit-test
    platform: iOS
    sources: iOSWithCarthageProjTests
    dependencies:
      - target: iOSWithCarthageProj
