name: CustomBuildConfig
options:
  bundleIdPrefix: com.mothule
configs:
  Debug: debug
  CI: debug
  Beta: release
  AppStore: release
targets:
  CustomBuildConfig:
    type: application
    platform: iOS
    sources: CustomBuildConfig
    settings:
      configs:
        CI:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: [DEBUG, DISABLE_ASSERTION]
  CustomBuildConfigTests:
    type: bundle.unit-test
    platform: iOS
    sources: CustomBuildConfigTests
    dependencies:
      - target: CustomBuildConfig

schemes:
  CustomBuildConfig:
    build:
      targets:
        CustomBuildConfig: all
        CustomBuildConfigTests: [test]
    test:
      targets:
        - CustomBuildConfigTests
      config: CI
      gatherCoverageData: true
      
