name: EmbeddedFramework
options:
  bundleIdPrefix: com.mothule
targets:
  EmbeddedFramework:
    type: application
    platform: iOS
    sources: EmbeddedFramework
    dependencies:
      - target: Logic
  Logic:
    type: framework
    platform: iOS
    sources:
      - path: Logic
